Feat!: Atomic latency option added to Ansible
dashevo/dash-network-deploy pull request #255
Opened 2021-08-31 12:29 UTC by ktechmidas

## Issue being fixed or feature implemented

To add "random" latency at the network level to the masternode servers through Ansible in order to test Platform under latency more similar to how mainnet operates. This will apply to devnet/testnet only

## What was done?
* Two roles have been added to ansible as the underlying Linux command is not atomic
  * The first is to add network latency if latency == 1 in the ansible vars
  * The second will set the latency to nothing if latency variable is 0

Note that right now we are simply using a shell command to achieve this as there is no underlying Ansible module which can add latency. This will be revisited later with an actual module...

## How Has This Been Tested?

Tested by bringing up my own devnet and applying the modules then attempting a simple ping.

* With latency = 0 (default)

ubuntu@masternode-4:~$ ping google.com
PING google.com (142.250.217.78) 56(84) bytes of data.
64 bytes from sea09s29-in-f14.1e100.net (142.250.217.78): icmp_seq=1 ttl=90 time=8.54 ms
64 bytes from sea09s29-in-f14.1e100.net (142.250.217.78): icmp_seq=2 ttl=90 time=8.53 ms

* With latency = 1

buntu@masternode-4:~$ ping google.com
PING google.com (142.250.217.78) 56(84) bytes of data.
64 bytes from sea09s29-in-f14.1e100.net (142.250.217.78): icmp_seq=1 ttl=90 time=108 ms
64 bytes from sea09s29-in-f14.1e100.net (142.250.217.78): icmp_seq=2 ttl=90 time=102 ms

## Breaking Changes

## Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated relevant unit/integration/functional/e2e tests
- [ ] I have made corresponding changes to the documentation

**For repository code-owners and collaborators only**
- [ ] I have assigned this pull request to a milestone

2021-09-01 11:21 UTC, shumkov commented
I wouldn't consider it as a breaking change since it's a new functionality so if you don't touch it then everything works the same as before.

2021-09-01 11:21 UTC, shumkov commented on ansible/deploy.yml
> +      when: latency == 1
It seems for other variables in the project we use booleans.

2021-09-01 11:22 UTC, shumkov commented on ansible/group_vars/all
> +latency: 0
What if call it more specific like `masternodes_network_latency`?

2021-09-07 09:28 UTC, shumkov commented on ansible/group_vars/all
> +latency_max: 100
```suggestion
masternode_network_latency_min: 10
masternode_network_latency_max: 100
```
latency_max: 100

2021-09-07 09:30 UTC, shumkov commented
As we discussed the latency thing affects deployment speed too. Is it possible to disable latency before we do deploy and enable it back as the last step?

2021-09-08 04:13 UTC, shumkov requested changes

2021-09-08 04:13 UTC, shumkov commented on ansible/deploy.yml
> -- hosts: all
It seems you commited something wrong

2021-09-08 06:49 UTC, ktechmidas commented on ansible/deploy.yml
> -- hosts: all
Correct, I was testing... fixed it :|

2021-09-08 09:14 UTC, shumkov approved these changes
LGTM 👍

2021-09-08 09:22 UTC, merged